---
title: "VIF_analysis_Ungulate_Traits"
output: html_document
---

#VIF Analysis 

#Set WD and install packages

```{r install}
source("https://raw.githubusercontent.com/naturalis/angiosperm-traits/master/phyloglmstep.R")
library(usdm)
library(phylolm)
library(corrplot)
library(dplyr)
library(caret)
library(ape)
library(ggplot2)
library(Rphylopars)
library(tidyverse)
library(phylogram)
```

Load data:

```{r load}
Ungulate <- read.csv("UngulateTraits.csv", sep = ',', header = TRUE)
GIS_Ungulate <- read.csv("https://raw.githubusercontent.com/naturalis/trait-geo-diverse-ungulates/master/results/OMI/niche_traits.csv")
row.names(GIS_Ungulate) <- GIS_Ungulate$X
row.names(Ungulate) <- Ungulate$CanonicalName
Merged_Data <- merge(Ungulate,GIS_Ungulate, by= "row.names")
rm(GIS_Ungulate, Ungulate)
```

#VIF analysis

```{r}
#creating predictor set
predictors <- Merged_Data[,c(10:103)]

#Removing collums with single states
newpredictor <- select(predictors,!c(Motility,ParentalCare,X12.2_Terrestriality,X2.1_AgeatEyeOpening_d,X))

#removing traits with sparse values 
newpredictor <- select(newpredictor, !c(X8.1_AdultForearmLen_mm, X18.1_BasalMetRate_mLO2hr, X5.2_BasalMetRateMass_g, X7.1_DispersalAge_d, X16.1_LittersPerYear, X13.2_NeonateHeadBodyLen_mm, X10.1_PopulationGrpSize, X13.3_WeaningHeadBodyLen_mm, X5.4_WeaningBodyMass_g))
```



```{r}
#VIF

Threshholds <- c(0.9,0.8,0.7,0.6,0.5,0.4,0.3)
for(thr in Threshholds){
  matrix <- cor(newpredictor, use = "pairwise.complete.obs")

  Collumstodelete <- findCorrelation(matrix, cutoff = thr, verbose = FALSE, exact=FALSE)

  newpredictor <- newpredictor[,-c(Collumstodelete)]
}


vif(newpredictor)

matrix <- cor(newpredictor, use = "pairwise.complete.obs")
corrplot(matrix, type="lower", order = "hclust", tl.pos = "l", tl.col = "black", tl.cex = 0.5)
```

```{r}

#remove food consumption and recompute VIF analysis

newpredictor <- select(newpredictor, !c(AVGFoodConsumption))


vif(newpredictor)


```

```{r}

Ungulatetree <- read.tree("https://raw.githubusercontent.com/naturalis/trait-organismal-ungulates/master/data/ungulates.tree")

# Which species aren't in the tree

Ungulatetree$tip.label <- gsub("_", " ", Ungulatetree$tip.label)
dropRows <- setdiff(Merged_Data$CanonicalName, Ungulatetree$tip.label)

# Drop rows that aren't in the tree, and aren't domesticated
row.names(Merged_Data) <- Merged_Data$CanonicalName
Merged_Data <- Merged_Data[!(row.names(Merged_Data) %in% dropRows), ]

#rename columns with dots in the name
Merged_Data <- Merged_Data %>% rename(Horns_Antlers = Horns.Antlers,
                              X21.1_PopulationDensity_n_km2 = X21.1_PopulationDensity_n.km2)
#remove traits that (almost) only consist of missing values (>100 NA)
Merged_Data <- subset(Merged_Data, select = -c(X5.4_WeaningBodyMass_g, X13.3_WeaningHeadBodyLen_mm, X13.2_NeonateHeadBodyLen_mm, X18.1_BasalMetRate_mLO2hr, X5.2_BasalMetRateMass_g, X2.1_AgeatEyeOpening_d, X8.1_AdultForearmLen_mm, X10.1_PopulationGrpSize))

#remove traits without any information gain (only consist of one value)
Merged_Data <- subset(Merged_Data, select = -c(Motility, ParentalCare, X12.2_Terrestriality))

#remove traits that are almost identical to other traits
Merged_Data <- subset(Merged_Data, select = -c(PullStrength, NumOffspring, BreedingInterval, 
                                       Diet, AVGWeight, MaturityReachFemale,
                                       MaturityReachMale, X22.2_HomeRange_Indiv_km2,
                                       X5.3_NeonateBodyMass_g,X16.1_LittersPerYear,X7.1_DispersalAge_d))

# Drop tips that aren't in dataset

dropTips <- setdiff(Ungulatetree$tip.label, Merged_Data$CanonicalName)
Ungulatetree <- drop.tip(Ungulatetree, dropTips)



#Complete cases

Merged_Data <- Merged_Data[complete.cases(Merged_Data),]

# Final check if there are any differences

setdiff(Merged_Data$CanonicalName, Ungulatetree$tip.label)
setdiff(Ungulatetree$tip.label, Merged_Data$CanonicalName)
rm(dropRows, dropTips)


```

```{r}

#Phyloglmstep

formula <- Domestication ~ Aspect + ClayPercentage + X1.1_ActivityCycle + X21.1_PopulationDensity_n.km2 + X10.2_SocialGrpSize + MaturityReachFemale + MatingSystem + BreedingInterval + YearRoundBreeding + Horns.Antlers + NaturalPredators + AVGMovingSpeed + AVGTravelDistance + OrganicCarbon

formula2 <- Domestication ~ X1.1_ActivityCycle + X5.1_AdultBodyMass_g + X21.1_PopulationDensity_n_km2 + X10.2_SocialGrpSize + MatingSystem + YearRoundBreeding + Horns_Antlers + AVGMovingSpeed + AVGTravelDistance + Aspect + ClayPercentage + OrganicCarbon

#Formula 1 with lowest VIF values and all traits
phyloglmstep(formula, starting.formula = NULL, data=Merged_Data, Ungulatetree, 
                         method = "logistic_MPLE",
                         direction = "forward", trace = 2,
                         btol = 10, log.alpha.bound = 4, start.beta=NULL, 
                         start.alpha=NULL, boot = 0, full.matrix = TRUE,
                         k=2) 
#Formula 2 without Habitat Breadth
phyloglmstep(formula2, starting.formula = NULL, data=Merged_Data, phy=Ungulatetree, 
             method="logistic_MPLE", direction = "forward", trace = 2, 
             btol = 10, log.alpha.bound = 4, start.beta=NULL, 
             start.alpha=NULL, boot = 0, full.matrix = TRUE, k=2)


```



